//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_GPVH.ServiceWSUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WS_GPVH")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Funcionario_run_sin_dvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Funcionario_run_sin_dv {
            get {
                return this.Funcionario_run_sin_dvField;
            }
            set {
                if ((this.Funcionario_run_sin_dvField.Equals(value) != true)) {
                    this.Funcionario_run_sin_dvField = value;
                    this.RaisePropertyChanged("Funcionario_run_sin_dv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_usuario {
            get {
                return this.Id_usuarioField;
            }
            set {
                if ((this.Id_usuarioField.Equals(value) != true)) {
                    this.Id_usuarioField = value;
                    this.RaisePropertyChanged("Id_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_usuario {
            get {
                return this.Nombre_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_usuarioField, value) != true)) {
                    this.Nombre_usuarioField = value;
                    this.RaisePropertyChanged("Nombre_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_usuario {
            get {
                return this.Tipo_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_usuarioField, value) != true)) {
                    this.Tipo_usuarioField = value;
                    this.RaisePropertyChanged("Tipo_usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWSUsuarios.IWSUsuarios")]
    public interface IWSUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/getListadoUsuarios", ReplyAction="http://tempuri.org/IWSUsuarios/getListadoUsuariosResponse")]
        WF_GPVH.ServiceWSUsuarios.Usuario[] getListadoUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/getListadoUsuarios", ReplyAction="http://tempuri.org/IWSUsuarios/getListadoUsuariosResponse")]
        System.Threading.Tasks.Task<WF_GPVH.ServiceWSUsuarios.Usuario[]> getListadoUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/getUsuarioById", ReplyAction="http://tempuri.org/IWSUsuarios/getUsuarioByIdResponse")]
        WF_GPVH.ServiceWSUsuarios.Usuario getUsuarioById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/getUsuarioById", ReplyAction="http://tempuri.org/IWSUsuarios/getUsuarioByIdResponse")]
        System.Threading.Tasks.Task<WF_GPVH.ServiceWSUsuarios.Usuario> getUsuarioByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/addUsuario", ReplyAction="http://tempuri.org/IWSUsuarios/addUsuarioResponse")]
        int addUsuario(string nombre, string clave, string tipo, int run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/addUsuario", ReplyAction="http://tempuri.org/IWSUsuarios/addUsuarioResponse")]
        System.Threading.Tasks.Task<int> addUsuarioAsync(string nombre, string clave, string tipo, int run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/modifyUsuario", ReplyAction="http://tempuri.org/IWSUsuarios/modifyUsuarioResponse")]
        int modifyUsuario(int id, string nombre, string clave, string tipo, int run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/modifyUsuario", ReplyAction="http://tempuri.org/IWSUsuarios/modifyUsuarioResponse")]
        System.Threading.Tasks.Task<int> modifyUsuarioAsync(int id, string nombre, string clave, string tipo, int run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/deleteUsuario", ReplyAction="http://tempuri.org/IWSUsuarios/deleteUsuarioResponse")]
        int deleteUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/deleteUsuario", ReplyAction="http://tempuri.org/IWSUsuarios/deleteUsuarioResponse")]
        System.Threading.Tasks.Task<int> deleteUsuarioAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSUsuariosChannel : WF_GPVH.ServiceWSUsuarios.IWSUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSUsuariosClient : System.ServiceModel.ClientBase<WF_GPVH.ServiceWSUsuarios.IWSUsuarios>, WF_GPVH.ServiceWSUsuarios.IWSUsuarios {
        
        public WSUsuariosClient() {
        }
        
        public WSUsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSUsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSUsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSUsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WF_GPVH.ServiceWSUsuarios.Usuario[] getListadoUsuarios() {
            return base.Channel.getListadoUsuarios();
        }
        
        public System.Threading.Tasks.Task<WF_GPVH.ServiceWSUsuarios.Usuario[]> getListadoUsuariosAsync() {
            return base.Channel.getListadoUsuariosAsync();
        }
        
        public WF_GPVH.ServiceWSUsuarios.Usuario getUsuarioById(int id) {
            return base.Channel.getUsuarioById(id);
        }
        
        public System.Threading.Tasks.Task<WF_GPVH.ServiceWSUsuarios.Usuario> getUsuarioByIdAsync(int id) {
            return base.Channel.getUsuarioByIdAsync(id);
        }
        
        public int addUsuario(string nombre, string clave, string tipo, int run) {
            return base.Channel.addUsuario(nombre, clave, tipo, run);
        }
        
        public System.Threading.Tasks.Task<int> addUsuarioAsync(string nombre, string clave, string tipo, int run) {
            return base.Channel.addUsuarioAsync(nombre, clave, tipo, run);
        }
        
        public int modifyUsuario(int id, string nombre, string clave, string tipo, int run) {
            return base.Channel.modifyUsuario(id, nombre, clave, tipo, run);
        }
        
        public System.Threading.Tasks.Task<int> modifyUsuarioAsync(int id, string nombre, string clave, string tipo, int run) {
            return base.Channel.modifyUsuarioAsync(id, nombre, clave, tipo, run);
        }
        
        public int deleteUsuario(int id) {
            return base.Channel.deleteUsuario(id);
        }
        
        public System.Threading.Tasks.Task<int> deleteUsuarioAsync(int id) {
            return base.Channel.deleteUsuarioAsync(id);
        }
    }
}
