//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_GPVH.ServiceWSReportes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilaReportePermisos", Namespace="http://schemas.datacontract.org/2004/07/WS_GPVH.WebServices.Reportes")]
    [System.SerializableAttribute()]
    public partial class FilaReportePermisos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_permisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_permiso {
            get {
                return this.Tipo_permisoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_permisoField, value) != true)) {
                    this.Tipo_permisoField = value;
                    this.RaisePropertyChanged("Tipo_permiso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidad {
            get {
                return this.UnidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadField, value) != true)) {
                    this.UnidadField = value;
                    this.RaisePropertyChanged("Unidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Antecedentes", Namespace="http://schemas.datacontract.org/2004/07/WS_GPVH.WebServices.Reportes")]
    [System.SerializableAttribute()]
    public partial class Antecedentes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Feriados_anuales_restantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WF_GPVH.ServiceWSReportes.FilaReporteAntecedentes[] FilasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Permisos_administrativos_restantesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Feriados_anuales_restantes {
            get {
                return this.Feriados_anuales_restantesField;
            }
            set {
                if ((this.Feriados_anuales_restantesField.Equals(value) != true)) {
                    this.Feriados_anuales_restantesField = value;
                    this.RaisePropertyChanged("Feriados_anuales_restantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WF_GPVH.ServiceWSReportes.FilaReporteAntecedentes[] Filas {
            get {
                return this.FilasField;
            }
            set {
                if ((object.ReferenceEquals(this.FilasField, value) != true)) {
                    this.FilasField = value;
                    this.RaisePropertyChanged("Filas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Permisos_administrativos_restantes {
            get {
                return this.Permisos_administrativos_restantesField;
            }
            set {
                if ((this.Permisos_administrativos_restantesField.Equals(value) != true)) {
                    this.Permisos_administrativos_restantesField = value;
                    this.RaisePropertyChanged("Permisos_administrativos_restantes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilaReporteAntecedentes", Namespace="http://schemas.datacontract.org/2004/07/WS_GPVH.WebServices.Reportes")]
    [System.SerializableAttribute()]
    public partial class FilaReporteAntecedentes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_permisoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_permiso {
            get {
                return this.Tipo_permisoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_permisoField, value) != true)) {
                    this.Tipo_permisoField = value;
                    this.RaisePropertyChanged("Tipo_permiso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWSReportes.IWSReportes")]
    public interface IWSReportes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSReportes/ReportePermisos", ReplyAction="http://tempuri.org/IWSReportes/ReportePermisosResponse")]
        WF_GPVH.ServiceWSReportes.FilaReportePermisos[] ReportePermisos(System.DateTime inicio, System.DateTime termino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSReportes/ReportePermisos", ReplyAction="http://tempuri.org/IWSReportes/ReportePermisosResponse")]
        System.Threading.Tasks.Task<WF_GPVH.ServiceWSReportes.FilaReportePermisos[]> ReportePermisosAsync(System.DateTime inicio, System.DateTime termino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSReportes/ReporteAntecedentes", ReplyAction="http://tempuri.org/IWSReportes/ReporteAntecedentesResponse")]
        WF_GPVH.ServiceWSReportes.Antecedentes ReporteAntecedentes(int run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSReportes/ReporteAntecedentes", ReplyAction="http://tempuri.org/IWSReportes/ReporteAntecedentesResponse")]
        System.Threading.Tasks.Task<WF_GPVH.ServiceWSReportes.Antecedentes> ReporteAntecedentesAsync(int run);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSReportesChannel : WF_GPVH.ServiceWSReportes.IWSReportes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSReportesClient : System.ServiceModel.ClientBase<WF_GPVH.ServiceWSReportes.IWSReportes>, WF_GPVH.ServiceWSReportes.IWSReportes {
        
        public WSReportesClient() {
        }
        
        public WSReportesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSReportesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSReportesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSReportesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WF_GPVH.ServiceWSReportes.FilaReportePermisos[] ReportePermisos(System.DateTime inicio, System.DateTime termino) {
            return base.Channel.ReportePermisos(inicio, termino);
        }
        
        public System.Threading.Tasks.Task<WF_GPVH.ServiceWSReportes.FilaReportePermisos[]> ReportePermisosAsync(System.DateTime inicio, System.DateTime termino) {
            return base.Channel.ReportePermisosAsync(inicio, termino);
        }
        
        public WF_GPVH.ServiceWSReportes.Antecedentes ReporteAntecedentes(int run) {
            return base.Channel.ReporteAntecedentes(run);
        }
        
        public System.Threading.Tasks.Task<WF_GPVH.ServiceWSReportes.Antecedentes> ReporteAntecedentesAsync(int run) {
            return base.Channel.ReporteAntecedentesAsync(run);
        }
    }
}
