//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_GPVH.ServiceWSFuncionarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://schemas.datacontract.org/2004/07/WS_GPVH.WebServices.Funcionarios")]
    [System.SerializableAttribute()]
    public partial class Funcionario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ap_maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ap_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Direc_funcionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_nacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_funcionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Run_dvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Run_sin_dvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_funcionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Unidad_id_unidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ap_materno {
            get {
                return this.Ap_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ap_maternoField, value) != true)) {
                    this.Ap_maternoField = value;
                    this.RaisePropertyChanged("Ap_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ap_paterno {
            get {
                return this.Ap_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ap_paternoField, value) != true)) {
                    this.Ap_paternoField = value;
                    this.RaisePropertyChanged("Ap_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direc_funcionario {
            get {
                return this.Direc_funcionarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Direc_funcionarioField, value) != true)) {
                    this.Direc_funcionarioField = value;
                    this.RaisePropertyChanged("Direc_funcionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_nacimiento {
            get {
                return this.Fec_nacimientoField;
            }
            set {
                if ((this.Fec_nacimientoField.Equals(value) != true)) {
                    this.Fec_nacimientoField = value;
                    this.RaisePropertyChanged("Fec_nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((this.HabilitadoField.Equals(value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_funcionario {
            get {
                return this.Nom_funcionarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_funcionarioField, value) != true)) {
                    this.Nom_funcionarioField = value;
                    this.RaisePropertyChanged("Nom_funcionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Run_dv {
            get {
                return this.Run_dvField;
            }
            set {
                if ((this.Run_dvField.Equals(value) != true)) {
                    this.Run_dvField = value;
                    this.RaisePropertyChanged("Run_dv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Run_sin_dv {
            get {
                return this.Run_sin_dvField;
            }
            set {
                if ((this.Run_sin_dvField.Equals(value) != true)) {
                    this.Run_sin_dvField = value;
                    this.RaisePropertyChanged("Run_sin_dv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_funcionario {
            get {
                return this.Tipo_funcionarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_funcionarioField, value) != true)) {
                    this.Tipo_funcionarioField = value;
                    this.RaisePropertyChanged("Tipo_funcionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Unidad_id_unidad {
            get {
                return this.Unidad_id_unidadField;
            }
            set {
                if ((this.Unidad_id_unidadField.Equals(value) != true)) {
                    this.Unidad_id_unidadField = value;
                    this.RaisePropertyChanged("Unidad_id_unidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWSFuncionarios.IWSFuncionarios")]
    public interface IWSFuncionarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/getListadoFuncionarios", ReplyAction="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosResponse")]
        WF_GPVH.ServiceWSFuncionarios.Funcionario[] getListadoFuncionarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/getListadoFuncionarios", ReplyAction="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosResponse")]
        System.Threading.Tasks.Task<WF_GPVH.ServiceWSFuncionarios.Funcionario[]> getListadoFuncionariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosClaveValor", ReplyAction="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosClaveValorResponse")]
        System.Collections.Generic.Dictionary<int, string> getListadoFuncionariosClaveValor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosClaveValor", ReplyAction="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosClaveValorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> getListadoFuncionariosClaveValorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosNoJefesClaveValor", ReplyAction="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosNoJefesClaveValorRespons" +
            "e")]
        System.Collections.Generic.Dictionary<int, string> getListadoFuncionariosNoJefesClaveValor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosNoJefesClaveValor", ReplyAction="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosNoJefesClaveValorRespons" +
            "e")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> getListadoFuncionariosNoJefesClaveValorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosNoJefesNoClaveValorModif" +
            "icar", ReplyAction="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosNoJefesNoClaveValorModif" +
            "icarResponse")]
        System.Collections.Generic.Dictionary<int, string> getListadoFuncionariosNoJefesNoClaveValorModificar(int id_unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosNoJefesNoClaveValorModif" +
            "icar", ReplyAction="http://tempuri.org/IWSFuncionarios/getListadoFuncionariosNoJefesNoClaveValorModif" +
            "icarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> getListadoFuncionariosNoJefesNoClaveValorModificarAsync(int id_unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/getFuncionarioByRun", ReplyAction="http://tempuri.org/IWSFuncionarios/getFuncionarioByRunResponse")]
        WF_GPVH.ServiceWSFuncionarios.Funcionario getFuncionarioByRun(int run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/getFuncionarioByRun", ReplyAction="http://tempuri.org/IWSFuncionarios/getFuncionarioByRunResponse")]
        System.Threading.Tasks.Task<WF_GPVH.ServiceWSFuncionarios.Funcionario> getFuncionarioByRunAsync(int run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/addFuncionario", ReplyAction="http://tempuri.org/IWSFuncionarios/addFuncionarioResponse")]
        int addFuncionario(int run, int dv, string nombre, string ap_pat, string ap_mat, System.DateTime nacimiento, string correo, string direccion, string tipo_funcionario, int id_unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/addFuncionario", ReplyAction="http://tempuri.org/IWSFuncionarios/addFuncionarioResponse")]
        System.Threading.Tasks.Task<int> addFuncionarioAsync(int run, int dv, string nombre, string ap_pat, string ap_mat, System.DateTime nacimiento, string correo, string direccion, string tipo_funcionario, int id_unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/modifyFuncionario", ReplyAction="http://tempuri.org/IWSFuncionarios/modifyFuncionarioResponse")]
        int modifyFuncionario(int run, string nombre, string ap_pat, string ap_mat, System.DateTime nacimiento, string correo, string direccion, string tipo_funcionario, bool habilitado_bool, int id_unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/modifyFuncionario", ReplyAction="http://tempuri.org/IWSFuncionarios/modifyFuncionarioResponse")]
        System.Threading.Tasks.Task<int> modifyFuncionarioAsync(int run, string nombre, string ap_pat, string ap_mat, System.DateTime nacimiento, string correo, string direccion, string tipo_funcionario, bool habilitado_bool, int id_unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/deleteFuncionario", ReplyAction="http://tempuri.org/IWSFuncionarios/deleteFuncionarioResponse")]
        int deleteFuncionario(int run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSFuncionarios/deleteFuncionario", ReplyAction="http://tempuri.org/IWSFuncionarios/deleteFuncionarioResponse")]
        System.Threading.Tasks.Task<int> deleteFuncionarioAsync(int run);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSFuncionariosChannel : WF_GPVH.ServiceWSFuncionarios.IWSFuncionarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSFuncionariosClient : System.ServiceModel.ClientBase<WF_GPVH.ServiceWSFuncionarios.IWSFuncionarios>, WF_GPVH.ServiceWSFuncionarios.IWSFuncionarios {
        
        public WSFuncionariosClient() {
        }
        
        public WSFuncionariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSFuncionariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFuncionariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFuncionariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WF_GPVH.ServiceWSFuncionarios.Funcionario[] getListadoFuncionarios() {
            return base.Channel.getListadoFuncionarios();
        }
        
        public System.Threading.Tasks.Task<WF_GPVH.ServiceWSFuncionarios.Funcionario[]> getListadoFuncionariosAsync() {
            return base.Channel.getListadoFuncionariosAsync();
        }
        
        public System.Collections.Generic.Dictionary<int, string> getListadoFuncionariosClaveValor() {
            return base.Channel.getListadoFuncionariosClaveValor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> getListadoFuncionariosClaveValorAsync() {
            return base.Channel.getListadoFuncionariosClaveValorAsync();
        }
        
        public System.Collections.Generic.Dictionary<int, string> getListadoFuncionariosNoJefesClaveValor() {
            return base.Channel.getListadoFuncionariosNoJefesClaveValor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> getListadoFuncionariosNoJefesClaveValorAsync() {
            return base.Channel.getListadoFuncionariosNoJefesClaveValorAsync();
        }
        
        public System.Collections.Generic.Dictionary<int, string> getListadoFuncionariosNoJefesNoClaveValorModificar(int id_unidad) {
            return base.Channel.getListadoFuncionariosNoJefesNoClaveValorModificar(id_unidad);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> getListadoFuncionariosNoJefesNoClaveValorModificarAsync(int id_unidad) {
            return base.Channel.getListadoFuncionariosNoJefesNoClaveValorModificarAsync(id_unidad);
        }
        
        public WF_GPVH.ServiceWSFuncionarios.Funcionario getFuncionarioByRun(int run) {
            return base.Channel.getFuncionarioByRun(run);
        }
        
        public System.Threading.Tasks.Task<WF_GPVH.ServiceWSFuncionarios.Funcionario> getFuncionarioByRunAsync(int run) {
            return base.Channel.getFuncionarioByRunAsync(run);
        }
        
        public int addFuncionario(int run, int dv, string nombre, string ap_pat, string ap_mat, System.DateTime nacimiento, string correo, string direccion, string tipo_funcionario, int id_unidad) {
            return base.Channel.addFuncionario(run, dv, nombre, ap_pat, ap_mat, nacimiento, correo, direccion, tipo_funcionario, id_unidad);
        }
        
        public System.Threading.Tasks.Task<int> addFuncionarioAsync(int run, int dv, string nombre, string ap_pat, string ap_mat, System.DateTime nacimiento, string correo, string direccion, string tipo_funcionario, int id_unidad) {
            return base.Channel.addFuncionarioAsync(run, dv, nombre, ap_pat, ap_mat, nacimiento, correo, direccion, tipo_funcionario, id_unidad);
        }
        
        public int modifyFuncionario(int run, string nombre, string ap_pat, string ap_mat, System.DateTime nacimiento, string correo, string direccion, string tipo_funcionario, bool habilitado_bool, int id_unidad) {
            return base.Channel.modifyFuncionario(run, nombre, ap_pat, ap_mat, nacimiento, correo, direccion, tipo_funcionario, habilitado_bool, id_unidad);
        }
        
        public System.Threading.Tasks.Task<int> modifyFuncionarioAsync(int run, string nombre, string ap_pat, string ap_mat, System.DateTime nacimiento, string correo, string direccion, string tipo_funcionario, bool habilitado_bool, int id_unidad) {
            return base.Channel.modifyFuncionarioAsync(run, nombre, ap_pat, ap_mat, nacimiento, correo, direccion, tipo_funcionario, habilitado_bool, id_unidad);
        }
        
        public int deleteFuncionario(int run) {
            return base.Channel.deleteFuncionario(run);
        }
        
        public System.Threading.Tasks.Task<int> deleteFuncionarioAsync(int run) {
            return base.Channel.deleteFuncionarioAsync(run);
        }
    }
}
