//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB_GPVH.ServiceWSPermisos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWSPermisos.IWSPermisos")]
    public interface IWSPermisos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPermisos/getPermisosByFuncionario", ReplyAction="http://tempuri.org/IWSPermisos/getPermisosByFuncionarioResponse")]
        WS_GPVH.WebServices.Permisos.Permiso[] getPermisosByFuncionario(int run, int condicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPermisos/getPermisosByFuncionario", ReplyAction="http://tempuri.org/IWSPermisos/getPermisosByFuncionarioResponse")]
        System.Threading.Tasks.Task<WS_GPVH.WebServices.Permisos.Permiso[]> getPermisosByFuncionarioAsync(int run, int condicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPermisos/getDocumentosByPermiso", ReplyAction="http://tempuri.org/IWSPermisos/getDocumentosByPermisoResponse")]
        WS_GPVH.WebServices.Permisos.Documento[] getDocumentosByPermiso(int id_permiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPermisos/getDocumentosByPermiso", ReplyAction="http://tempuri.org/IWSPermisos/getDocumentosByPermisoResponse")]
        System.Threading.Tasks.Task<WS_GPVH.WebServices.Permisos.Documento[]> getDocumentosByPermisoAsync(int id_permiso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSPermisosChannel : LB_GPVH.ServiceWSPermisos.IWSPermisos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPermisosClient : System.ServiceModel.ClientBase<LB_GPVH.ServiceWSPermisos.IWSPermisos>, LB_GPVH.ServiceWSPermisos.IWSPermisos {
        
        public WSPermisosClient() {
        }
        
        public WSPermisosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPermisosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPermisosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPermisosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WS_GPVH.WebServices.Permisos.Permiso[] getPermisosByFuncionario(int run, int condicion) {
            return base.Channel.getPermisosByFuncionario(run, condicion);
        }
        
        public System.Threading.Tasks.Task<WS_GPVH.WebServices.Permisos.Permiso[]> getPermisosByFuncionarioAsync(int run, int condicion) {
            return base.Channel.getPermisosByFuncionarioAsync(run, condicion);
        }
        
        public WS_GPVH.WebServices.Permisos.Documento[] getDocumentosByPermiso(int id_permiso) {
            return base.Channel.getDocumentosByPermiso(id_permiso);
        }
        
        public System.Threading.Tasks.Task<WS_GPVH.WebServices.Permisos.Documento[]> getDocumentosByPermisoAsync(int id_permiso) {
            return base.Channel.getDocumentosByPermisoAsync(id_permiso);
        }
    }
}
